/**
 * Native theme tokens — generated by Style Dictionary from DTCG themes
 * (tokens/dtcg/themes/{light,dark}.json). Do not edit by hand.
 * Run: pnpm build:tokens
 *
 * Concrete hex maps for React Native (no CSS vars, no rem). Consumed by
 * providers/native.ts so the native theme mirrors the DTCG themes rather
 * than re-hardcoding the palette.
 */

export const nativeThemeLight = {
  "background": "#ffffff",
  "foreground": "#09090b",
  "card": "#ffffff",
  "cardForeground": "#09090b",
  "popover": "#ffffff",
  "popoverForeground": "#09090b",
  "primaryForeground": "#ffffff",
  "secondary": "#f4f4f5",
  "secondaryForeground": "#18181b",
  "muted": "#f4f4f5",
  "mutedForeground": "#71717a",
  "accent": "#f4f4f5",
  "accentForeground": "#18181b",
  "destructive": "#ef4444",
  "destructiveForeground": "#fafafa",
  "border": "#e4e4e7",
  "input": "#e4e4e7",
  "success": "#10b981",
  "successForeground": "#ffffff",
  "warning": "#f59e0b",
  "warningForeground": "#ffffff",
  "info": "#3b82f6",
  "infoForeground": "#ffffff",
  "chart1": "#e8725c",
  "chart2": "#2a9d8f",
  "chart3": "#264653",
  "chart4": "#e9c46a",
  "chart5": "#f4a261",
  "sidebarBackground": "#fafafa",
  "sidebarForeground": "#3f3f46",
  "sidebarAccent": "#f4f4f5",
  "sidebarAccentForeground": "#18181b",
  "sidebarBorder": "#e5e7eb",
  "sidebarPrimaryForeground": "#ffffff"
} as const;

export const nativeThemeDark = {
  "background": "#09090b",
  "foreground": "#fafafa",
  "card": "#09090b",
  "cardForeground": "#fafafa",
  "popover": "#09090b",
  "popoverForeground": "#fafafa",
  "primaryForeground": "#09090b",
  "secondary": "#27272a",
  "secondaryForeground": "#fafafa",
  "muted": "#27272a",
  "mutedForeground": "#a1a1aa",
  "accent": "#27272a",
  "accentForeground": "#fafafa",
  "destructive": "#7f1d1d",
  "destructiveForeground": "#fafafa",
  "border": "#27272a",
  "input": "#27272a",
  "success": "#22c997",
  "successForeground": "#ffffff",
  "warning": "#f59e0b",
  "warningForeground": "#ffffff",
  "info": "#3b82f6",
  "infoForeground": "#ffffff",
  "chart1": "#3b82f6",
  "chart2": "#34d399",
  "chart3": "#f59e0b",
  "chart4": "#a78bfa",
  "chart5": "#f472b6",
  "sidebarBackground": "#18181b",
  "sidebarForeground": "#f4f4f5",
  "sidebarAccent": "#27272a",
  "sidebarAccentForeground": "#f4f4f5",
  "sidebarBorder": "#27272a",
  "sidebarPrimaryForeground": "#ffffff"
} as const;
