/**
 * Native tokens — generated by Style Dictionary from DTCG tokens.
 * Do not edit by hand. Run: pnpm build:tokens
 *
 * All values are concrete (hex colors, px numbers). No CSS vars, no rem.
 */

export const nativeColors = {
  neutral: {
      "50": "#FAFAFA",
      "100": "#F4F4F5",
      "200": "#E4E4E7",
      "300": "#D4D8DD",
      "400": "#A1A1AA",
      "500": "#71717A",
      "600": "#52525B",
      "700": "#3F3F46",
      "800": "#27272A",
      "900": "#18181B"
  },
  semantic: {
      "success": {
          "DEFAULT": "#10B981",
          "light": "#D1FAE5",
          "dark": "#065F46"
      },
      "warning": {
          "DEFAULT": "#F59E0B",
          "light": "#FEF3C7",
          "dark": "#92400E"
      },
      "error": {
          "DEFAULT": "#EF4444",
          "light": "#FEE2E2",
          "dark": "#991B1B"
      },
      "info": {
          "DEFAULT": "#3B82F6",
          "light": "#DBEAFE",
          "dark": "#1E40AF"
      }
  },
  status: {
      "active": "#10B981",
      "inactive": "#A1A1AA",
      "pending": "#F59E0B",
      "blocked": "#EF4444",
      "draft": "#71717A",
      "archived": "#D4D8DD",
      "onTrack": "#10B981",
      "atRisk": "#F59E0B",
      "offTrack": "#EF4444",
      "done": "#10B981",
      "inProgress": "#3B82F6"
  },
} as const;

export const nativeSpacing = {
  "page-x": 16,
  "page-sm": 24,
  "page-lg": 32,
  "card-padding": 20,
  "section-gap": 32
} as const;

export const nativeRadius = {
  "sm": 4,
  "md": 6,
  "lg": 8,
  "xl": 12,
  "full": 9999
} as const;

export const nativeFontSize = {
  "xs": 12,
  "sm": 14,
  "base": 16,
  "lg": 18,
  "xl": 20,
  "2xl": 24,
  "3xl": 30
} as const;

export const nativeLineHeight = {
  "xs": 16,
  "sm": 20,
  "base": 24,
  "lg": 28,
  "xl": 28,
  "2xl": 32,
  "3xl": 36
} as const;

export const nativeFontWeight = {
  "normal": 400,
  "medium": 500,
  "semibold": 600,
  "bold": 700
} as const;

export const nativeFontFamily = {
  "sans": "Inter, ui-sans-serif, system-ui, sans-serif",
  "display": "Space Grotesk, ui-sans-serif, system-ui, sans-serif",
  "mono": "ui-monospace, SFMono-Regular, SF Mono, Menlo, monospace"
} as const;

export const nativeTypography = {
  "h1": {
    "fontSize": 30,
    "lineHeight": 36,
    "fontWeight": 700
  },
  "h2": {
    "fontSize": 24,
    "lineHeight": 32,
    "fontWeight": 700
  },
  "h3": {
    "fontSize": 20,
    "lineHeight": 28,
    "fontWeight": 600
  },
  "h4": {
    "fontSize": 18,
    "lineHeight": 28,
    "fontWeight": 600
  },
  "body": {
    "fontSize": 16,
    "lineHeight": 24,
    "fontWeight": 400
  },
  "body-sm": {
    "fontSize": 14,
    "lineHeight": 20,
    "fontWeight": 400
  },
  "caption": {
    "fontSize": 12,
    "lineHeight": 16,
    "fontWeight": 400
  }
} as const;
