/**
 * Style Dictionary v4 build configuration.
 *
 * Generates:
 *   - dist/themes/{brand}.css  (one per brand, Shadcn HSL-component format)
 *   - dist/tokens/native.ts    (hex colors + px numbers for React Native)
 *
 * Run: pnpm build:tokens
 */

import StyleDictionary from "style-dictionary";
import type {
  TransformedToken,
  FormatFnArguments,
  Config,
} from "style-dictionary/types";
import { readFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// ---------------------------------------------------------------------------
// Brand definitions (HSL values for primary, matching existing presets)
// ---------------------------------------------------------------------------

interface BrandDef {
  name: string;
  h: number;
  s: number;
  l: number;
  radius: string;
}

// v0.2.0 (PRD-07 Phase A2): only the brand-genesis OOTB fallback ships
// from Genesis. Other brand presets and their DTCG token JSONs moved into
// their consumer's `@<consumer>/brand` package.
const brands: BrandDef[] = [
  { name: "genesis", h: 160, s: 84, l: 39, radius: "0.625rem" },
];

// ---------------------------------------------------------------------------
// Helpers: hex -> HSL component string (Shadcn format: "160 84% 39%")
// ---------------------------------------------------------------------------

function hexToHslComponents(hex: string): string {
  if (!/^#[0-9a-fA-F]{6}$/.test(hex)) {
    throw new Error(`[style-dictionary] Expected 6-digit hex color, got: "${hex}". Check your DTCG token files.`);
  }
  const r = parseInt(hex.slice(1, 3), 16) / 255;
  const g = parseInt(hex.slice(3, 5), 16) / 255;
  const b = parseInt(hex.slice(5, 7), 16) / 255;
  const max = Math.max(r, g, b);
  const min = Math.min(r, g, b);
  const l = (max + min) / 2;
  if (max === min) return `0 0% ${round(l * 100)}%`;
  const d = max - min;
  const s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
  let h = 0;
  if (max === r) h = ((g - b) / d + (g < b ? 6 : 0)) / 6;
  else if (max === g) h = ((b - r) / d + 2) / 6;
  else h = ((r - g) / d + 4) / 6;
  return `${round(h * 360)} ${round(s * 100)}% ${round(l * 100)}%`;
}

function round(n: number): number {
  return Math.round(n * 10) / 10;
}

// ---------------------------------------------------------------------------
// Custom format: Shadcn CSS variables (HSL components, no hsl() wrapper)
// ---------------------------------------------------------------------------

function shadcnCssFormat(brand: BrandDef) {
  return {
    name: `css/shadcn-${brand.name}`,
    format: async ({ dictionary }: FormatFnArguments) => {
      const { h, s, l, radius } = brand;
      const darkL = Math.min(l + 10, 80);

      const fontDisplay = `"Space Grotesk", ui-sans-serif, system-ui, sans-serif`;

      const css = `/**
 * ${brand.name} theme — generated by Style Dictionary from DTCG tokens.
 * Do not edit by hand. Run: pnpm build:tokens
 */

:root {
  --background: 0 0% 100%;
  --foreground: 240 10% 3.9%;
  --card: 0 0% 100%;
  --card-foreground: 240 10% 3.9%;
  --popover: 0 0% 100%;
  --popover-foreground: 240 10% 3.9%;
  --primary: ${h} ${s}% ${l}%;
  --primary-foreground: 0 0% 100%;
  --secondary: 240 4.8% 95.9%;
  --secondary-foreground: 240 5.9% 10%;
  --muted: 240 4.8% 95.9%;
  --muted-foreground: 240 3.8% 46.1%;
  --accent: 240 4.8% 95.9%;
  --accent-foreground: 240 5.9% 10%;
  --destructive: 0 84.2% 60.2%;
  --destructive-foreground: 0 0% 98%;
  --border: 240 5.9% 90%;
  --input: 240 5.9% 90%;
  --ring: ${h} ${s}% ${l}%;
  --radius: ${radius};
  --chart-1: 12 76% 61%;
  --chart-2: 173 58% 39%;
  --chart-3: 197 37% 24%;
  --chart-4: 43 74% 66%;
  --chart-5: 27 87% 67%;

  /* Semantic status colors */
  --success: 160 84.1% 39.4%;
  --success-foreground: 0 0% 100%;
  --warning: 38 92.1% 50.2%;
  --warning-foreground: 0 0% 100%;
  --info: 217 91.2% 59.8%;
  --info-foreground: 0 0% 100%;

  /* Sidebar */
  --sidebar-background: 0 0% 98%;
  --sidebar-foreground: 240 5.3% 26.1%;
  --sidebar-primary: ${h} ${s}% ${l}%;
  --sidebar-primary-foreground: 0 0% 100%;
  --sidebar-accent: 240 4.8% 95.9%;
  --sidebar-accent-foreground: 240 5.9% 10%;
  --sidebar-border: 220 13% 91%;
  --sidebar-ring: ${h} ${s}% ${l}%;

  /* Typography */
  --font-display: ${fontDisplay};
}

.dark {
  --background: 240 10% 3.9%;
  --foreground: 0 0% 98%;
  --card: 240 10% 3.9%;
  --card-foreground: 0 0% 98%;
  --popover: 240 10% 3.9%;
  --popover-foreground: 0 0% 98%;
  --primary: ${h} ${s}% ${darkL}%;
  --primary-foreground: 240 10% 3.9%;
  --secondary: 240 3.7% 15.9%;
  --secondary-foreground: 0 0% 98%;
  --muted: 240 3.7% 15.9%;
  --muted-foreground: 240 5% 64.9%;
  --accent: 240 3.7% 15.9%;
  --accent-foreground: 0 0% 98%;
  --destructive: 0 62.8% 30.6%;
  --destructive-foreground: 0 0% 98%;
  --border: 240 3.7% 15.9%;
  --input: 240 3.7% 15.9%;
  --ring: ${h} ${s}% ${darkL}%;
  --radius: ${radius};
  --chart-1: 220 70% 50%;
  --chart-2: 160 60% 45%;
  --chart-3: 30 80% 55%;
  --chart-4: 280 65% 60%;
  --chart-5: 340 75% 55%;

  /* Semantic status colors (dark) */
  --success: 160 84.1% 49%;
  --success-foreground: 0 0% 100%;
  --warning: 38 92.1% 50.2%;
  --warning-foreground: 0 0% 100%;
  --info: 217 91.2% 59.8%;
  --info-foreground: 0 0% 100%;

  /* Sidebar */
  --sidebar-background: 240 5.9% 10%;
  --sidebar-foreground: 240 4.8% 95.9%;
  --sidebar-primary: ${h} ${s}% ${darkL}%;
  --sidebar-primary-foreground: 0 0% 100%;
  --sidebar-accent: 240 3.7% 15.9%;
  --sidebar-accent-foreground: 240 4.8% 95.9%;
  --sidebar-border: 240 3.7% 15.9%;
  --sidebar-ring: ${h} ${s}% ${darkL}%;

  /* Typography */
  --font-display: ${fontDisplay};
}
`;
      return css;
    },
  };
}

// ---------------------------------------------------------------------------
// Custom format: Native TypeScript tokens (hex + px numbers)
// ---------------------------------------------------------------------------

const nativeTsFormat = {
  name: "ts/native-tokens",
  format: async ({ dictionary }: FormatFnArguments) => {
    // In DTCG mode, resolved values are on t.$value, not t.value
    function val(t: TransformedToken): unknown {
      return t.$value ?? t.value;
    }

    // Collect token groups
    const colorTokens = dictionary.allTokens.filter(
      (t) => t.$type === "color" && t.path[0] === "color"
    );
    const spacingTokens = dictionary.allTokens.filter(
      (t) => t.path[0] === "spacing"
    );
    const radiusTokens = dictionary.allTokens.filter(
      (t) => t.path[0] === "radius"
    );
    const fontSizeTokens = dictionary.allTokens.filter(
      (t) => t.path[0] === "font" && t.path[1] === "size"
    );
    const lineHeightTokens = dictionary.allTokens.filter(
      (t) => t.path[0] === "font" && t.path[1] === "lineHeight"
    );
    const fontWeightTokens = dictionary.allTokens.filter(
      (t) => t.path[0] === "font" && t.path[1] === "weight"
    );
    const fontFamilyTokens = dictionary.allTokens.filter(
      (t) => t.path[0] === "font" && t.path[1] === "family"
    );

    function pxToNum(v: unknown): number {
      if (typeof v === "number") return v;
      const num = parseFloat(String(v).replace("px", ""));
      if (isNaN(num)) {
        throw new Error(`[style-dictionary] Cannot convert "${v}" to number. Check your DTCG token files.`);
      }
      return num;
    }

    // Build neutral colors
    const neutralObj: Record<string, string> = {};
    for (const t of colorTokens) {
      if (t.path[1] === "neutral") {
        neutralObj[t.path[2]] = val(t) as string;
      }
    }

    // Build semantic colors
    const semanticObj: Record<string, Record<string, string>> = {};
    for (const t of colorTokens) {
      if (t.path[1] === "semantic") {
        const group = t.path[2];
        if (!semanticObj[group]) semanticObj[group] = {};
        semanticObj[group][t.path[3]] = val(t) as string;
      }
    }

    // Build status colors (resolve references)
    const statusObj: Record<string, string> = {};
    for (const t of colorTokens) {
      if (t.path[1] === "status") {
        statusObj[t.path[2]] = val(t) as string;
      }
    }

    // Build spacing
    const spacingObj: Record<string, number> = {};
    for (const t of spacingTokens) {
      const key = t.path.slice(1).join("-");
      spacingObj[key] = pxToNum(val(t));
    }

    // Build radius
    const radiusObj: Record<string, number> = {};
    for (const t of radiusTokens) {
      const key = t.path[1];
      radiusObj[key] = pxToNum(val(t));
    }

    // Build font sizes
    const fontSizeObj: Record<string, number> = {};
    for (const t of fontSizeTokens) {
      fontSizeObj[t.path[2]] = pxToNum(val(t));
    }

    // Build line heights
    const lineHeightObj: Record<string, number> = {};
    for (const t of lineHeightTokens) {
      lineHeightObj[t.path[2]] = pxToNum(val(t));
    }

    // Build font weights
    const fontWeightObj: Record<string, number> = {};
    for (const t of fontWeightTokens) {
      const v = val(t);
      fontWeightObj[t.path[2]] = typeof v === "number" ? v : parseInt(String(v), 10);
    }

    // Build font families
    const fontFamilyObj: Record<string, string> = {};
    for (const t of fontFamilyTokens) {
      fontFamilyObj[t.path[2]] = val(t) as string;
    }

    // Build typography presets from composite DTCG tokens
    const typographyPresets: Record<string, { fontSize: number; lineHeight: number; fontWeight: number }> = {};
    const presetTokens = dictionary.allTokens.filter(
      (t) => t.path[0] === "font" && t.path[1] === "presets"
    );
    for (const t of presetTokens) {
      const v = val(t);
      if (v && typeof v === "object") {
        const obj = v as Record<string, unknown>;
        typographyPresets[t.path[2]] = {
          fontSize: pxToNum(String(obj.fontSize)),
          lineHeight: pxToNum(String(obj.lineHeight)),
          fontWeight: typeof obj.fontWeight === "number" ? obj.fontWeight : parseInt(String(obj.fontWeight), 10),
        };
      }
    }

    return `/**
 * Native tokens — generated by Style Dictionary from DTCG tokens.
 * Do not edit by hand. Run: pnpm build:tokens
 *
 * All values are concrete (hex colors, px numbers). No CSS vars, no rem.
 */

export const nativeColors = {
  neutral: ${JSON.stringify(neutralObj, null, 4).replace(/\n/g, "\n  ")},
  semantic: ${JSON.stringify(semanticObj, null, 4).replace(/\n/g, "\n  ")},
  status: ${JSON.stringify(statusObj, null, 4).replace(/\n/g, "\n  ")},
} as const;

export const nativeSpacing = ${JSON.stringify(spacingObj, null, 2)} as const;

export const nativeRadius = ${JSON.stringify(radiusObj, null, 2)} as const;

export const nativeFontSize = ${JSON.stringify(fontSizeObj, null, 2)} as const;

export const nativeLineHeight = ${JSON.stringify(lineHeightObj, null, 2)} as const;

export const nativeFontWeight = ${JSON.stringify(fontWeightObj, null, 2)} as const;

export const nativeFontFamily = ${JSON.stringify(fontFamilyObj, null, 2)} as const;

export const nativeTypography = ${JSON.stringify(typographyPresets, null, 2)} as const;
`;
  },
};

// ---------------------------------------------------------------------------
// Custom format: Native theme tokens (light/dark concrete hex maps)
//
// The DTCG theme files (themes/light.json, themes/dark.json) define the SAME
// token paths with different values, so they cannot be merged into a single
// Style Dictionary dictionary. Their values are reference-free concrete hex,
// so this format reads both files directly and flattens each into a concrete
// `{ camelCaseName: hex }` map — emitting `nativeThemeLight` + `nativeThemeDark`
// so React Native code (providers/native.ts) consumes the DTCG themes instead
// of re-hardcoding the palette. Regenerated by `pnpm build:tokens`, exactly
// like src/tokens/native.ts.
// ---------------------------------------------------------------------------

function camelCaseKey(key: string): string {
  return key.replace(/-([a-zA-Z0-9])/g, (_, c: string) => c.toUpperCase());
}

/** Flatten a DTCG `theme` node into a concrete `{ camelCaseName: hex }` map. */
function flattenThemeColors(
  themeNode: Record<string, unknown>
): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [key, node] of Object.entries(themeNode)) {
    if (!node || typeof node !== "object") continue;
    const rec = node as Record<string, unknown>;
    if (typeof rec.$value === "string") {
      out[camelCaseKey(key)] = rec.$value;
      continue;
    }
    // Nested group (e.g. `sidebar`) — flatten one level with a prefix.
    for (const [subKey, subNode] of Object.entries(rec)) {
      if (
        subNode &&
        typeof subNode === "object" &&
        typeof (subNode as Record<string, unknown>).$value === "string"
      ) {
        out[camelCaseKey(`${key}-${subKey}`)] = (
          subNode as Record<string, unknown>
        ).$value as string;
      }
    }
  }
  return out;
}

function readNativeTheme(themeFile: string): Record<string, string> {
  const raw = readFileSync(
    join(__dirname, "tokens", "dtcg", "themes", themeFile),
    "utf8"
  );
  const parsed = JSON.parse(raw) as { theme?: Record<string, unknown> };
  if (!parsed.theme) {
    throw new Error(
      `[style-dictionary] ${themeFile} has no top-level "theme" object.`
    );
  }
  return flattenThemeColors(parsed.theme);
}

const nativeThemeTsFormat = {
  name: "ts/native-theme-tokens",
  format: async () => {
    const light = readNativeTheme("light.json");
    const dark = readNativeTheme("dark.json");
    return `/**
 * Native theme tokens — generated by Style Dictionary from DTCG themes
 * (tokens/dtcg/themes/{light,dark}.json). Do not edit by hand.
 * Run: pnpm build:tokens
 *
 * Concrete hex maps for React Native (no CSS vars, no rem). Consumed by
 * providers/native.ts so the native theme mirrors the DTCG themes rather
 * than re-hardcoding the palette.
 */

export const nativeThemeLight = ${JSON.stringify(light, null, 2)} as const;

export const nativeThemeDark = ${JSON.stringify(dark, null, 2)} as const;
`;
  },
};

// ---------------------------------------------------------------------------
// Build function
// ---------------------------------------------------------------------------

async function build() {
  const tokensDir = join(__dirname, "tokens", "dtcg");

  // Build target selector (CLI arg): "all" (default) | "native" | "css".
  //
  // The two outputs land in different places and have opposite ordering needs
  // vs the package's `tsup` bundle (which has `clean: true`, wiping dist/):
  //   - native  → src/tokens/*.ts  MUST be generated BEFORE tsup so the bundled
  //               dist reflects the current DTCG values (not one build behind).
  //   - css     → dist/themes/*.css MUST be generated AFTER tsup's clean, or it
  //               gets wiped.
  // So package.json's build script runs `build:tokens:native && tsup &&
  // build:tokens:css`. The bare "all" target stays available for standalone /
  // manual regeneration.
  const target = process.argv[2] ?? "all";
  const doNative = target === "all" || target === "native";
  const doCss = target === "all" || target === "css";
  if (!doNative && !doCss) {
    throw new Error(
      `[style-dictionary] Unknown build target "${target}". Use one of: all | native | css.`
    );
  }

  // Register all custom formats
  for (const brand of brands) {
    const fmt = shadcnCssFormat(brand);
    StyleDictionary.registerFormat({
      name: fmt.name,
      format: fmt.format,
    });
  }

  StyleDictionary.registerFormat({
    name: nativeTsFormat.name,
    format: nativeTsFormat.format,
  });

  StyleDictionary.registerFormat({
    name: nativeThemeTsFormat.name,
    format: nativeThemeTsFormat.format,
  });

  // Build one CSS file per brand (→ dist/themes/; run AFTER tsup clean).
  if (doCss) {
    for (const brand of brands) {
      const sd = new StyleDictionary({
        source: [
          join(tokensDir, "colors.json"),
          join(tokensDir, "spacing.json"),
          join(tokensDir, "typography.json"),
          join(tokensDir, "themes", "light.json"),
          join(tokensDir, "brands", `${brand.name}.json`),
        ],
        platforms: {
          css: {
            transformGroup: "css",
            buildPath: join(__dirname, "dist", "themes") + "/",
            files: [
              {
                destination: `${brand.name}.css`,
                format: `css/shadcn-${brand.name}`,
              },
            ],
          },
        },
      });

      await sd.buildAllPlatforms();
      console.log(`  wrote dist/themes/${brand.name}.css`);
    }
  }

  // Native token generation (→ src/tokens/; run BEFORE tsup bundles).
  if (doNative) {
  // Build native tokens (brand-agnostic base tokens)
  const sdNative = new StyleDictionary({
    source: [
      join(tokensDir, "colors.json"),
      join(tokensDir, "spacing.json"),
      join(tokensDir, "typography.json"),
    ],
    platforms: {
      native: {
        transforms: ["attribute/cti", "name/kebab"],
        buildPath: join(__dirname, "src", "tokens") + "/",
        files: [
          {
            destination: "native.ts",
            format: "ts/native-tokens",
          },
        ],
      },
    },
  });

  await sdNative.buildAllPlatforms();
  console.log("  wrote src/tokens/native.ts");

  // Build native theme tokens (light/dark concrete hex maps from DTCG themes).
  // The format reads both theme files directly (see nativeThemeTsFormat above),
  // so the single source here just satisfies Style Dictionary's requirement.
  const sdNativeTheme = new StyleDictionary({
    source: [join(tokensDir, "themes", "light.json")],
    platforms: {
      nativeTheme: {
        transforms: ["attribute/cti", "name/kebab"],
        buildPath: join(__dirname, "src", "tokens") + "/",
        files: [
          {
            destination: "native-themes.ts",
            format: "ts/native-theme-tokens",
          },
        ],
      },
    },
  });

  await sdNativeTheme.buildAllPlatforms();
  console.log("  wrote src/tokens/native-themes.ts");
  }

  const built = [
    doCss ? `${brands.length} CSS theme(s)` : null,
    doNative ? "native tokens + native themes" : null,
  ]
    .filter(Boolean)
    .join(" + ");
  console.log(`\nDone — generated ${built}.`);
}

build().catch((err) => {
  console.error(err);
  process.exit(1);
});
