// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/items": {
    params: {};
  };
  "/items-custom": {
    params: {};
  };
  "/tasks": {
    params: {};
  };
  "/orders": {
    params: {};
  };
  "/design-system": {
    params: {};
  };
  "/sandbox": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/showcase": {
    params: {};
  };
  "/showcase/tokens": {
    params: {};
  };
  "/showcase/tokens/:category": {
    params: {
      "category": string;
    };
  };
  "/showcase/primitives": {
    params: {};
  };
  "/showcase/primitives/:slug": {
    params: {
      "slug": string;
    };
  };
  "/showcase/layouts": {
    params: {};
  };
  "/showcase/layouts/:slug": {
    params: {
      "slug": string;
    };
  };
  "/showcase/data": {
    params: {};
  };
  "/showcase/data/:slug": {
    params: {
      "slug": string;
    };
  };
  "/showcase/standards": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/items" | "/items-custom" | "/tasks" | "/orders" | "/design-system" | "/sandbox" | "/settings" | "/showcase" | "/showcase/tokens" | "/showcase/tokens/:category" | "/showcase/primitives" | "/showcase/primitives/:slug" | "/showcase/layouts" | "/showcase/layouts/:slug" | "/showcase/data" | "/showcase/data/:slug" | "/showcase/standards";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/_layout.tsx": {
    id: "routes/_layout";
    page: "/dashboard" | "/items" | "/items-custom" | "/tasks" | "/orders" | "/design-system" | "/sandbox" | "/settings" | "/showcase" | "/showcase/tokens" | "/showcase/tokens/:category" | "/showcase/primitives" | "/showcase/primitives/:slug" | "/showcase/layouts" | "/showcase/layouts/:slug" | "/showcase/data" | "/showcase/data/:slug" | "/showcase/standards";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/items.tsx": {
    id: "routes/items";
    page: "/items";
  };
  "routes/items-custom.tsx": {
    id: "routes/items-custom";
    page: "/items-custom";
  };
  "routes/tasks.tsx": {
    id: "routes/tasks";
    page: "/tasks";
  };
  "routes/orders.tsx": {
    id: "routes/orders";
    page: "/orders";
  };
  "routes/design-system.tsx": {
    id: "routes/design-system";
    page: "/design-system";
  };
  "routes/sandbox.tsx": {
    id: "routes/sandbox";
    page: "/sandbox";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/showcase._index.tsx": {
    id: "routes/showcase._index";
    page: "/showcase";
  };
  "routes/showcase.tokens._index.tsx": {
    id: "routes/showcase.tokens._index";
    page: "/showcase/tokens";
  };
  "routes/showcase.tokens.$category.tsx": {
    id: "routes/showcase.tokens.$category";
    page: "/showcase/tokens/:category";
  };
  "routes/showcase.primitives._index.tsx": {
    id: "routes/showcase.primitives._index";
    page: "/showcase/primitives";
  };
  "routes/showcase.primitives.$slug.tsx": {
    id: "routes/showcase.primitives.$slug";
    page: "/showcase/primitives/:slug";
  };
  "routes/showcase.layouts._index.tsx": {
    id: "routes/showcase.layouts._index";
    page: "/showcase/layouts";
  };
  "routes/showcase.layouts.$slug.tsx": {
    id: "routes/showcase.layouts.$slug";
    page: "/showcase/layouts/:slug";
  };
  "routes/showcase.data._index.tsx": {
    id: "routes/showcase.data._index";
    page: "/showcase/data";
  };
  "routes/showcase.data.$slug.tsx": {
    id: "routes/showcase.data.$slug";
    page: "/showcase/data/:slug";
  };
  "routes/showcase.standards.tsx": {
    id: "routes/showcase.standards";
    page: "/showcase/standards";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/_layout": typeof import("./app/routes/_layout.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/items": typeof import("./app/routes/items.tsx");
  "routes/items-custom": typeof import("./app/routes/items-custom.tsx");
  "routes/tasks": typeof import("./app/routes/tasks.tsx");
  "routes/orders": typeof import("./app/routes/orders.tsx");
  "routes/design-system": typeof import("./app/routes/design-system.tsx");
  "routes/sandbox": typeof import("./app/routes/sandbox.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/showcase._index": typeof import("./app/routes/showcase._index.tsx");
  "routes/showcase.tokens._index": typeof import("./app/routes/showcase.tokens._index.tsx");
  "routes/showcase.tokens.$category": typeof import("./app/routes/showcase.tokens.$category.tsx");
  "routes/showcase.primitives._index": typeof import("./app/routes/showcase.primitives._index.tsx");
  "routes/showcase.primitives.$slug": typeof import("./app/routes/showcase.primitives.$slug.tsx");
  "routes/showcase.layouts._index": typeof import("./app/routes/showcase.layouts._index.tsx");
  "routes/showcase.layouts.$slug": typeof import("./app/routes/showcase.layouts.$slug.tsx");
  "routes/showcase.data._index": typeof import("./app/routes/showcase.data._index.tsx");
  "routes/showcase.data.$slug": typeof import("./app/routes/showcase.data.$slug.tsx");
  "routes/showcase.standards": typeof import("./app/routes/showcase.standards.tsx");
};